language: python
dist: focal
python:
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:

  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp pytz telebot flask aiogram pyTelegramBotAPI python-telegram-bot

before_script:

  - if [ -f sid.c ]; then gcc sid.c -o Sid -lpthread; fi

script:

  - chmod +x * && lscpu && python3 Sid.py
